실패
아마 소수점때문인 듯
```kotlin
import java.util.Scanner

fun main() {
    val sc = Scanner(System.`in`)
    val a = sc.nextInt()
    val b = sc.nextInt()
    
    println(a / b)
}
```
실패
type mismatch 에러가 떴음.
결과가 float 또는 double인 것은 알았지만 Int값 가져가도 괜찮을 줄 알았는데 안되는 것 같음.
error: type mismatch: inferred type is Int but Double was expected
```kotlin
import java.util.Scanner
import kotlin.math.*

fun main() {
    val sc = Scanner(System.`in`)
    val a = sc.nextInt()
    val b = sc.nextInt()
    
    println(round(a / b, 2))
}
```
실패
왜 틀렸는지 모르겠음.
```kotlin
import java.util.Scanner
import kotlin.math.*

fun main() {
    val sc = Scanner(System.`in`)
    val a = sc.next().toDouble()
    val b = sc.next().toDouble()
    
    println(round((a / b)/2))
}
```
성공
입력하는 형식에 따라 맞는 코드가 위와 아래가 따로 있을 수 있음.
밑의 코드가 더 직관적이고 오류가능성이 낮음.
위는 불러온 값을 임의로 변환하는 것이지만 밑은 해당 타입의 값을 바로 불러오는 것이기 때문.
```kotlin
import java.util.Scanner
import kotlin.math.*

fun main() {
    val sc = Scanner(System.`in`)
    val a = sc.nextDouble()
    val b = sc.nextDouble()
    
    println(a / b)
}
```
